# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import spotlight_pb2 as spotlight__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in spotlight_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedLearningServiceStub(object):
    """Federated Learning Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGlobalModel = channel.unary_unary(
                '/spotlight.FederatedLearningService/GetGlobalModel',
                request_serializer=spotlight__pb2.ModelVersion.SerializeToString,
                response_deserializer=spotlight__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.SendModelWeights = channel.unary_unary(
                '/spotlight.FederatedLearningService/SendModelWeights',
                request_serializer=spotlight__pb2.ModelWeights.SerializeToString,
                response_deserializer=spotlight__pb2.Ack.FromString,
                _registered_method=True)
        self.registerClient = channel.unary_unary(
                '/spotlight.FederatedLearningService/registerClient',
                request_serializer=spotlight__pb2.clientInfo.SerializeToString,
                response_deserializer=spotlight__pb2.Ack.FromString,
                _registered_method=True)


class FederatedLearningServiceServicer(object):
    """Federated Learning Service definition
    """

    def GetGlobalModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModelWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registerClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=spotlight__pb2.ModelVersion.FromString,
                    response_serializer=spotlight__pb2.ModelResponse.SerializeToString,
            ),
            'SendModelWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModelWeights,
                    request_deserializer=spotlight__pb2.ModelWeights.FromString,
                    response_serializer=spotlight__pb2.Ack.SerializeToString,
            ),
            'registerClient': grpc.unary_unary_rpc_method_handler(
                    servicer.registerClient,
                    request_deserializer=spotlight__pb2.clientInfo.FromString,
                    response_serializer=spotlight__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spotlight.FederatedLearningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spotlight.FederatedLearningService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedLearningService(object):
    """Federated Learning Service definition
    """

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotlight.FederatedLearningService/GetGlobalModel',
            spotlight__pb2.ModelVersion.SerializeToString,
            spotlight__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendModelWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotlight.FederatedLearningService/SendModelWeights',
            spotlight__pb2.ModelWeights.SerializeToString,
            spotlight__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def registerClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotlight.FederatedLearningService/registerClient',
            spotlight__pb2.clientInfo.SerializeToString,
            spotlight__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
