# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spotlight.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'spotlight.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspotlight.proto\x12\tspotlight\"\x1e\n\nclientInfo\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\"\x1f\n\x0cModelVersion\x12\x0f\n\x07version\x18\x01 \x01(\t\"1\n\rModelResponse\x12\x0f\n\x07weights\x18\x01 \x03(\x02\x12\x0f\n\x07version\x18\x02 \x01(\t\"j\n\x0cModelWeights\x12\x0f\n\x07weights\x18\x01 \x03(\x02\x12\x13\n\x0bnum_samples\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x02\x12\x0f\n\x07version\x18\x04 \x01(\x05\x12\x10\n\x08\x63lientId\x18\x05 \x01(\t\"8\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07weights\x18\x03 \x03(\x02\x32\xd5\x01\n\x18\x46\x65\x64\x65ratedLearningService\x12\x43\n\x0eGetGlobalModel\x12\x17.spotlight.ModelVersion\x1a\x18.spotlight.ModelResponse\x12;\n\x10SendModelWeights\x12\x17.spotlight.ModelWeights\x1a\x0e.spotlight.Ack\x12\x37\n\x0eregisterClient\x12\x15.spotlight.clientInfo\x1a\x0e.spotlight.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spotlight_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTINFO']._serialized_start=30
  _globals['_CLIENTINFO']._serialized_end=60
  _globals['_MODELVERSION']._serialized_start=62
  _globals['_MODELVERSION']._serialized_end=93
  _globals['_MODELRESPONSE']._serialized_start=95
  _globals['_MODELRESPONSE']._serialized_end=144
  _globals['_MODELWEIGHTS']._serialized_start=146
  _globals['_MODELWEIGHTS']._serialized_end=252
  _globals['_ACK']._serialized_start=254
  _globals['_ACK']._serialized_end=310
  _globals['_FEDERATEDLEARNINGSERVICE']._serialized_start=313
  _globals['_FEDERATEDLEARNINGSERVICE']._serialized_end=526
# @@protoc_insertion_point(module_scope)
