# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spotlight.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'spotlight.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspotlight.proto\x12\x0e\x45mulatedClient\x1a\x1bgoogle/protobuf/empty.proto\"\x0e\n\x0cModelRequest\"\xe7\x01\n\rModelResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12K\n\x10model_state_dict\x18\x02 \x03(\x0b\x32\x31.EmulatedClient.ModelResponse.ModelStateDictEntry\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12\x16\n\x0eglobal_version\x18\x04 \x01(\x05\x12\x18\n\x10\x65mulated_clients\x18\x05 \x03(\t\x1a\x35\n\x13ModelStateDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"O\n\rWeightsUpdate\x12\x15\n\rmodel_weights\x18\x01 \x03(\x02\x12\x13\n\x0bnum_samples\x18\x02 \x01(\x05\x12\x12\n\nmodel_type\x18\x03 \x01(\t\"\x1e\n\x0cModelWeights\x12\x0e\n\x06values\x18\x01 \x03(\x02\"!\n\x0eUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9e\x01\n\x0cModelService\x12@\n\x08GetModel\x12\x1c.EmulatedClient.ModelRequest\x1a\x16.google.protobuf.Empty\x12L\n\x0bUpdateModel\x12\x1d.EmulatedClient.WeightsUpdate\x1a\x1e.EmulatedClient.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spotlight_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELRESPONSE_MODELSTATEDICTENTRY']._loaded_options = None
  _globals['_MODELRESPONSE_MODELSTATEDICTENTRY']._serialized_options = b'8\001'
  _globals['_MODELREQUEST']._serialized_start=64
  _globals['_MODELREQUEST']._serialized_end=78
  _globals['_MODELRESPONSE']._serialized_start=81
  _globals['_MODELRESPONSE']._serialized_end=312
  _globals['_MODELRESPONSE_MODELSTATEDICTENTRY']._serialized_start=259
  _globals['_MODELRESPONSE_MODELSTATEDICTENTRY']._serialized_end=312
  _globals['_WEIGHTSUPDATE']._serialized_start=314
  _globals['_WEIGHTSUPDATE']._serialized_end=393
  _globals['_MODELWEIGHTS']._serialized_start=395
  _globals['_MODELWEIGHTS']._serialized_end=425
  _globals['_UPDATERESPONSE']._serialized_start=427
  _globals['_UPDATERESPONSE']._serialized_end=460
  _globals['_MODELSERVICE']._serialized_start=463
  _globals['_MODELSERVICE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
