# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spotlight.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'spotlight.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspotlight.proto\x12\tsimplecnn\"\"\n\x0cModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"\xc8\x01\n\rModelResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x46\n\x10model_state_dict\x18\x02 \x03(\x0b\x32,.simplecnn.ModelResponse.ModelStateDictEntry\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12\x16\n\x0eglobal_version\x18\x04 \x01(\x05\x1a\x35\n\x13ModelStateDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\xad\x02\n\rWeightsUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x41\n\rmodel_weights\x18\x03 \x03(\x0b\x32*.simplecnn.WeightsUpdate.ModelWeightsEntry\x12\x13\n\x0bnum_samples\x18\x04 \x01(\x05\x12\x0c\n\x04loss\x18\x05 \x01(\x02\x12\x0f\n\x07version\x18\x06 \x01(\x05\x12\x1c\n\x14\x43lient_training_time\x18\x07 \x01(\x02\x12\x12\n\ncompressed\x18\x08 \x01(\x08\x1aL\n\x11ModelWeightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.simplecnn.ModelWeights:\x02\x38\x01\":\n\x0cModelWeights\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\x1a\n\x12\x63ompressed_weights\x18\x02 \x01(\x0c\"\x84\x01\n\x0eUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x18\n\x10model_state_dict\x18\x02 \x03(\x02\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12\x18\n\x10\x61ggregation_time\x18\x04 \x01(\x02\x12\x1c\n\x14\x63lient_training_time\x18\x05 \x01(\x02\x32\x91\x01\n\x0cModelService\x12=\n\x08GetModel\x12\x17.simplecnn.ModelRequest\x1a\x18.simplecnn.ModelResponse\x12\x42\n\x0bUpdateModel\x12\x18.simplecnn.WeightsUpdate\x1a\x19.simplecnn.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spotlight_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELRESPONSE_MODELSTATEDICTENTRY']._loaded_options = None
  _globals['_MODELRESPONSE_MODELSTATEDICTENTRY']._serialized_options = b'8\001'
  _globals['_WEIGHTSUPDATE_MODELWEIGHTSENTRY']._loaded_options = None
  _globals['_WEIGHTSUPDATE_MODELWEIGHTSENTRY']._serialized_options = b'8\001'
  _globals['_MODELREQUEST']._serialized_start=30
  _globals['_MODELREQUEST']._serialized_end=64
  _globals['_MODELRESPONSE']._serialized_start=67
  _globals['_MODELRESPONSE']._serialized_end=267
  _globals['_MODELRESPONSE_MODELSTATEDICTENTRY']._serialized_start=214
  _globals['_MODELRESPONSE_MODELSTATEDICTENTRY']._serialized_end=267
  _globals['_WEIGHTSUPDATE']._serialized_start=270
  _globals['_WEIGHTSUPDATE']._serialized_end=571
  _globals['_WEIGHTSUPDATE_MODELWEIGHTSENTRY']._serialized_start=495
  _globals['_WEIGHTSUPDATE_MODELWEIGHTSENTRY']._serialized_end=571
  _globals['_MODELWEIGHTS']._serialized_start=573
  _globals['_MODELWEIGHTS']._serialized_end=631
  _globals['_UPDATERESPONSE']._serialized_start=634
  _globals['_UPDATERESPONSE']._serialized_end=766
  _globals['_MODELSERVICE']._serialized_start=769
  _globals['_MODELSERVICE']._serialized_end=914
# @@protoc_insertion_point(module_scope)
